

// Pre-defined knowledge base for the student chat
const CANNED_RESPONSES = {
  "good moral": "To request a Good Moral Certificate, go to Good Moral Request, select your purpose, and submit. Processing typically takes 3–5 working days.",
  "appointment": "You can book a counseling appointment from the Appointment page. Choose an available date and time slot.",
  "office hours": "The Office of Guidance and Counseling (OGC) is open Monday–Friday, 8:00 AM–5:00 PM.",
  "location": "The OGC is located on the second floor of the Student Services Building.",
  "requirements": "Requirements depend on the specific service. For a Good Moral Certificate, you typically need your Student ID and academic clearance. Please check the specific service page for exact details.",
  "counseling": "We offer both online and face-to-face counseling. Everything you share is kept strictly confidential.",
  "status": "You can track the live status of your requests and appointments directly on your Student Dashboard."
};

export const aiService = {
  
  /**
   * MOCK function for Student AI Assistant.
   * Uses simple keyword matching to simulate AI comprehension.
   * @param {string} question - The user's input
   * @returns {Promise<string>} - The canned response
   */   
  askAssistant: async (question) => {
    const lowerQuestion = question.toLowerCase();
    
    // Find the first keyword that matches the user's question
    const matchedKey = Object.keys(CANNED_RESPONSES).find(key => 
      lowerQuestion.includes(key)
    );

    // Simulate network/LLM processing delay (600ms)
    await new Promise(resolve => setTimeout(resolve, 600));

    // Return matched canned response or default fallback
    return matchedKey 
      ? CANNED_RESPONSES[matchedKey] 
      : "I'm a demo assistant — this response is a placeholder. A real AI-powered answer will appear here once the backend AI service is integrated.";
  },

  /**
   * MOCK function for Admin AI Insights.
   * Takes raw analytics data and generates plain-language operational summaries.
   * This does NOT make new recommendations; it merely echoes the analytics data in English.
   * @param {Object} analytics - Data from analyticsService.getAnalyticsData()
   */
  generateAdminInsights: async (analytics) => {
    // Simulate generation delay (800ms)
    await new Promise(resolve => setTimeout(resolve, 800));

    if (!analytics || !analytics.kpis) {
        return {
            trendSummary: "Unable to generate insights: Analytics data is missing.",
            attentionAreas: [],
            draftReport: "Data unavailable for draft generation."
        };
    }

    const { kpis, summary, serviceBacklog } = analytics;
    
    // 1. Trend Summary Generation
    const trendSummary = `Over the selected period, the OGC received a total of ${kpis.totalRequests} requests. The overall completion rate stands at ${kpis.completionRate}%, with an average turnaround time of ${kpis.averageProcessingDays} days per request. Additionally, a total of ${summary.appointments.total} counseling appointments were processed.`;

    // 2. Areas Requiring Attention (Plain language echoes)
    const attentionAreas = [];
    
    if (summary.requests.pending > 0) {
        attentionAreas.push(`There are currently ${summary.requests.pending} pending requests awaiting initial review in the system.`);
    }
    
    // Check service backlog to see the most delayed service
    if (serviceBacklog && serviceBacklog.length > 0) {
        // Sort by highest pending
        const mostPendingService = [...serviceBacklog].sort((a, b) => b.pending - a.pending)[0];
        if (mostPendingService && mostPendingService.pending > 0) {
            attentionAreas.push(`The ${mostPendingService.service} service has the highest operational backlog with ${mostPendingService.pending} active requests.`);
        }
    }

    if (summary.appointments.noShow > 0) {
        attentionAreas.push(`There were ${summary.appointments.noShow} recorded no-show appointments recently.`);
    }

    if (attentionAreas.length === 0) {
        attentionAreas.push("All operational metrics are within normal ranges. No immediate bottlenecks detected.");
    }

    // 3. Draft Report Summary (For easy copy-pasting)
    const draftReport = `EXECUTIVE SUMMARY - GUIDANCE & COUNSELING OPERATIONS\n\n`
        + `${trendSummary}\n\n`
        + `KEY OPERATIONAL OBSERVATIONS:\n`
        + attentionAreas.map(item => `- ${item}`).join('\n')
        + `\n\n---\n*Report generated by OGC System (Demo AI).*`;

    return {
        trendSummary,
        attentionAreas,
        draftReport
    };
  }
};